---
- name: Build localhost
  hosts: localhost
  connection: local

  vars:
    upgrade_homebrew_packages: true
    mas_upgrade_all_apps: true

  tasks:
    - name: Check if Homebrew is already installed in /usr
      stat:
        path: /usr/local/bin/brew
      register: homebrew_local
      tags:
        - brew
        - brew-bundle

    - name: Check if Homebrew is already installed /opt
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_opt
      tags:
        - brew

    - fail:
        msg: Please perform the pre-req's in the README.md
      when: not homebrew_local.stat.exists and not homebrew_opt.stat.exists
      tags:
        - brew

    - name: Install brew bundles
      command: "brew bundle --file BrewFile -q "
      when: homebrew_local.stat.exists or homebrew_opt.stat.exists
      tags:
        - brew-bundle


    - name: include appstore_packages vars
      include_vars:
        file: appstore_packages.yml
      tags:
        - appstore

    - name: List installed MAS apps.
      command: mas list
      register: mas_list
      check_mode: false
      changed_when: false
      tags:
        - appstore

    - name: Ensure configured MAS apps are installed.
      command: mas install "{{ item.id|default(item) }}"
      with_items: "{{ appstore_packages }}"
      when: (item.id | default(item) | string) not in mas_list.stdout
      tags:
        - appstore

    - name: Upgrade all apps (if configured).
      command: mas upgrade
      when: mas_upgrade_all_apps
      tags:
        - appstore

    - name: include Login Packages vars
      include_vars:
        file: login_packages.yml
      tags:
        - login

    - name: Setup Apps to start at login
      shell: loginItems -a "{{ item }}"
      with_items:
        - "{{ login_packages }}"
      tags:
        - login


